sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDGrULGdBBeUK9nAvSm
    access-key-secret: su3JIAi83LdgyhuqwGcsmJ76KXGzzN
    bucket-name: sky-itcast-shuo
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx7f71cd9332679c79
    secret: 8500f757e7716a9a1eb122bfe314e28c

